name: sanal_portfoy_yonetim_simulasyonu
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.2
  google_fonts: ^3.0.1
  email_validator: ^2.0.1
  introduction_screen: ^3.0.2
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  animated_text_kit: ^4.2.2
  cloud_firestore: ^3.4.3
  firebase_core: ^1.20.0
  intl: ^0.17.0
  confetti: ^0.7.0
  font_awesome_flutter: ^10.1.0
  pie_chart: ^5.3.2
  modal_progress_hud_nsn: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/yapi_kredi_logo.png