// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0h0iABp0a8s81_Z-jdlu_khpHfUIwVQA',
    appId: '1:306698546908:web:1a3b96e50dab64e6488e19',
    messagingSenderId: '306698546908',
    projectId: 'sanalportfoyyonetimsimulasyonu',
    authDomain: 'sanalportfoyyonetimsimulasyonu.firebaseapp.com',
    storageBucket: 'sanalportfoyyonetimsimulasyonu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1P4UwbpUWtCqMmFnZiKGIoJBmGziV0Ck',
    appId: '1:306698546908:android:2b672e30f96b7e36488e19',
    messagingSenderId: '306698546908',
    projectId: 'sanalportfoyyonetimsimulasyonu',
    storageBucket: 'sanalportfoyyonetimsimulasyonu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCyQlCo5iJUhbnMbTkUFey7kV2mFMLg_s',
    appId: '1:306698546908:ios:66a5ddce064a82dc488e19',
    messagingSenderId: '306698546908',
    projectId: 'sanalportfoyyonetimsimulasyonu',
    storageBucket: 'sanalportfoyyonetimsimulasyonu.appspot.com',
    iosClientId: '306698546908-45kmp11uhcg66bk3tjltaki9hu47sil4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanalPortfoyYonetimSimulasyonu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCyQlCo5iJUhbnMbTkUFey7kV2mFMLg_s',
    appId: '1:306698546908:ios:66a5ddce064a82dc488e19',
    messagingSenderId: '306698546908',
    projectId: 'sanalportfoyyonetimsimulasyonu',
    storageBucket: 'sanalportfoyyonetimsimulasyonu.appspot.com',
    iosClientId: '306698546908-45kmp11uhcg66bk3tjltaki9hu47sil4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanalPortfoyYonetimSimulasyonu',
  );
}
